postgis: &postgis
  adapter: postgis
  host: localhost
  port: 5432
  username: matt
  password:


development:
  <<: *postgis
  database: notifiable-rails-development

test:
  <<: *postgis
  database: notifiable-rails-test


